### ISSUE TITLE
Decoded SATWND from ds351.0 still contains binary value

### ISSUE THREAD

**Issue by Nuo-Chen** [NCAR/rda-bufr-decode-ADPupa#2]
With the update rda bufr decoder, satwnd from ds351.0 does show the GOES data. But when I opened the output txt file, I noticed that a big chunk of data (starting with OBS TYPE = NC0050**) has the station number showing binary value `^@^@^@èvH7B`

` SATWND   NC005039  202008080200  ^@^@^@èvH7B   -38.74   -96.41  99999     1  WXPR   874.9  9999.9     999.9     999.9     999.9  999.9  999.9  999.9   124.0    12.5    |        0.00    271.00`

Another issue I encountered was when I tried to search the GOES data with either 'VISUS' or 'H2SUS' I couldn't find them. Their OBS TYPE are rather NC005030 and NC005031 as shown [here](https://github.com/wrf-model/WRF/blob/0a11865f97680fdd6865b278ea29d910e5db3ed7/var/da/da_obs_io/da_read_obs_bufr_satwnd.inc#L993)

**Comment by tcram** [comment]
@Nuo-Chen I will look into this.  To confirm, is the example you show above output from the BUFR SATWND file for 00 UTC 08 Aug 2020?

**Comment by Nuo-Chen** [comment]
Yes, the bufr file name is `gdas.satwnd.t00z.20200808.bufr`

**Comment by tcram** [comment]
@Nuo-Chen This should be fixed now.  The decoder was using the BUFR mnemonic `RPID` for the station column, but this value is undefined in SATWND observations.  The code is updated to use `SAID` instead for SATWND observations, and the station name field is increased from 8 characters to 40 characters to accommodate the larger size of the satellite ID value.

See pull request #3  for details.
